USE Merit
CREATE TABLE CONTACT_DET(CUS_NAME VARCHAR(20)NOT NULL,
CUS_MAIL_ID VARCHAR(50) NOT NULL,
CUS_MES VARCHAR(100)NOT NULL,
CreatedBy VARCHAR(20) NOT NULL,
CreateDate DATETIME NOT NULL,
ModifiedBy VARCHAR(20) NOT NULL,
ModifiedDate DATETIME NOT NULL,
RecordStatus BIT NOT NULL,
RowGUID VARCHAR(MAX));

SELECT * FROM CONTACT_DET
 

--INSERT
 CREATE PROCEDURE INSERT_CONTACT_DETAILS
 @C_NAME VARCHAR(10),
 @C_EMAIL VARCHAR(50),
 @C_MSG VARCHAR(100)
 AS
 BEGIN
 INSERT INTO CONTACT_DET VALUES(@C_NAME,@C_EMAIL,@C_MSG,CURRENT_USER, CURRENT_TIMESTAMP ,CURRENT_USER, CURRENT_TIMESTAMP, 1, NEWID())
 END
 EXEC INSERT_CONTACT_DETAILS 'AAA','ABC123@GMAIL.COM','MESSAGE1';
SELECT * FROM CONTACT_DET

--DELETE

CREATE PROCEDURE DELETE_CONTACT_DET

@C_NAME VARCHAR(50)

AS
BEGIN

DELETE FROM CONTACT_DET WHERE CUS_NAME=@C_NAME
END
EXEC  DELETE_CONTACT_DET 'AAA'

SELECT * FROM CONTACT_DET
--UPDATE
CREATE PROCEDURE UPD_CONTACT_DETAILS

@C_EMAIL VARCHAR(50),
@C_MSG VARCHAR(100)

AS
BEGIN

UPDATE CONTACT_DET SET CUS_MES=@C_MSG, ModifiedBy = CURRENT_USER, ModifiedDate = CURRENT_TIMESTAMP WHERE CUS_MAIL_ID=@C_EMAIL
END
EXEC UPD_CONTACT_DETAILS 'agila123@gmail.com','update message1'

SELECT * FROM CONTACT_DET

--LIST
CREATE PROCEDURE CONTACT
AS
BEGIN
SELECT * FROM CONTACT_DET;
END
